---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aniel928/public_html
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp education.html $DEPLOYPATH
    - /bin/cp experience.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp navbar.html $DEPLOYPATH
    - /bin/cp projects_details.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH